name: Python push

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-python-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Change to Custom Directory
        run: cd py

      - name: Install project dependencies
        run: poetry install

      - name: Build and publish Python package
        run: |
          poetry build
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}

secrets:
  PYPI_USERNAME: __token__
  PYPI_PASSWORD: pypi-AgEIcHlwaS5vcmcCJGYwZTAxZTA3LWFmYTctNGQ4YS05ZWFmLTIzNTQ0OWJkMTY0MwACKlszLCIyNTUwNzE3OC04YTAwLTQ4ZWYtOThiNy0wMWUzMjE0NGE4YmMiXQAABiAUzdSF_4YPxOS0B1lV4t8jA9G7Z-TISf_9JSZCmpW8ww
